// Mocks generated by Mockito 5.0.14 from annotations
// in case_app/test/bloc/application/aplication_bloc_test.dart.
// Do not manually edit this file.

import 'package:case_app/bloc/form_bloc/form_bloc.dart' as _i6;
import 'package:case_app/classes/aplication_info.dart/application_info.dart'
    as _i3;
import 'package:case_app/core/failure.dart' as _i5;
import 'package:case_app/data_handlers/savers/application_saver.dart' as _i7;
import 'package:case_app/data_handlers/submitters/application_submitter.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeApplicationInfo_1 extends _i1.Fake implements _i3.ApplicationInfo {}

/// A class which mocks [ApplicationSubmitter].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplicationSubmitter extends _i1.Mock
    implements _i4.ApplicationSubmitter {
  MockApplicationSubmitter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Either<_i5.Failure, void> submit(_i3.ApplicationInfo? info) =>
      (super.noSuchMethod(Invocation.method(#submit, [info]),
              returnValue: _FakeEither_0<_i5.Failure, void>())
          as _i2.Either<_i5.Failure, void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [InputFormEvent].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputFormEvent extends _i1.Mock implements _i6.InputFormEvent {
  MockInputFormEvent() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ApplicationSaver].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplicationSaver extends _i1.Mock implements _i7.ApplicationSaver {
  MockApplicationSaver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void saveData(_i6.InputFormEvent? event) =>
      super.noSuchMethod(Invocation.method(#saveData, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.ApplicationInfo fetchInfo() =>
      (super.noSuchMethod(Invocation.method(#fetchInfo, []),
          returnValue: _FakeApplicationInfo_1()) as _i3.ApplicationInfo);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ClientData].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientData extends _i1.Mock implements _i3.ClientData {
  MockClientData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set company(String? _company) =>
      super.noSuchMethod(Invocation.setter(#company, _company),
          returnValueForMissingStub: null);
  @override
  set name(String? _name) => super.noSuchMethod(Invocation.setter(#name, _name),
      returnValueForMissingStub: null);
  @override
  set phoneNumber(String? _phoneNumber) =>
      super.noSuchMethod(Invocation.setter(#phoneNumber, _phoneNumber),
          returnValueForMissingStub: null);
  @override
  set dateOfBirth(String? _dateOfBirth) =>
      super.noSuchMethod(Invocation.setter(#dateOfBirth, _dateOfBirth),
          returnValueForMissingStub: null);
  @override
  set gender(String? _gender) =>
      super.noSuchMethod(Invocation.setter(#gender, _gender),
          returnValueForMissingStub: null);
  @override
  set email(String? _email) =>
      super.noSuchMethod(Invocation.setter(#email, _email),
          returnValueForMissingStub: null);
  @override
  set address(String? _address) =>
      super.noSuchMethod(Invocation.setter(#address, _address),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DependantInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockDependantInfo extends _i1.Mock implements _i3.DependantInfo {
  MockDependantInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set name(String? _name) => super.noSuchMethod(Invocation.setter(#name, _name),
      returnValueForMissingStub: null);
  @override
  set gender(String? _gender) =>
      super.noSuchMethod(Invocation.setter(#gender, _gender),
          returnValueForMissingStub: null);
  @override
  set dateOfBirth(String? _dateOfBirth) =>
      super.noSuchMethod(Invocation.setter(#dateOfBirth, _dateOfBirth),
          returnValueForMissingStub: null);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  String toString() => super.toString();
}
