// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIOGTvl6GJA9--TWFKcg13WXlliG-1BDE',
    appId: '1:653130125039:web:ed05ea5ec06a4312ed151a',
    messagingSenderId: '653130125039',
    projectId: 'caseapp-8a255',
    authDomain: 'caseapp-8a255.firebaseapp.com',
    databaseURL: 'https://caseapp-8a255.firebaseio.com',
    storageBucket: 'caseapp-8a255.appspot.com',
    measurementId: 'G-PG61QKJG4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETju1TLjuzwzVW3ajqsgcR6HuGku7xhQ',
    appId: '1:653130125039:android:ef64f8936b8fc1d3ed151a',
    messagingSenderId: '653130125039',
    projectId: 'caseapp-8a255',
    databaseURL: 'https://caseapp-8a255.firebaseio.com',
    storageBucket: 'caseapp-8a255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0SIU7FLlaPiPMyTAIRXq7ox57nViPZRg',
    appId: '1:653130125039:ios:61af6748d2806f7eed151a',
    messagingSenderId: '653130125039',
    projectId: 'caseapp-8a255',
    databaseURL: 'https://caseapp-8a255.firebaseio.com',
    storageBucket: 'caseapp-8a255.appspot.com',
    androidClientId: '653130125039-1p9sdg2mliqs55ou5st82srq6kguahed.apps.googleusercontent.com',
    iosClientId: '653130125039-nldl0dp0bkb6b83st0uuvnln5seasipr.apps.googleusercontent.com',
    iosBundleId: 'com.faridorg.caseapp',
  );
}
